### ISSUE TITLE
Is `vows` supposed to be a devDependency?

### ISSUE THREAD

**Issue by bmathews** [winstonjs/winston-compat#4]
Looks like vows is a test helper, but is set as a dependency instead of a devDependency.

**Comment by douira** [comment]
And this version of vows introduces a bunch of deprecated packages as sub-dependencies which makes npm spew warnings on install.

**Comment by mattberther** [comment]
@indexzero I think we can close this.

**Comment by indexzero** [comment]
Thanks @mattberther
