### ISSUE TITLE
Regular Expression Denial of Service

### ISSUE THREAD

**Issue by spywhere** [winstonjs/winston-compat#5]
`winston-compat@0.1.0` currently using `vows@0.8.1` which vulnerable to RegExp DoS as the details below. Please update the dependencies accordingly to resolve the issue.

<img width="517" alt="screen shot 2561-04-17 at 11 56 26" src="https://user-images.githubusercontent.com/1087399/38849481-628d3294-4236-11e8-8656-9c2779c775be.png">

**Comment by mattberther** [comment]
#6 moved vows to a dev dependency. As such, I dont believe winston-compat is subject to this issue. Please re-open if you feel differently.
